# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Push

on:
  push:
    branches: ['*', '*/*', '!master']
  pull_request: 
    branches: ['*', '*/*']

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10', '12']

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ./node_modules
        key: ${{ matrix.node }}-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    
    - run: npm install
    - run: npm test